backend: gpu           # gpu|metal|vulkan|cpu

grid_size_x: 128
grid_size_y: 128

time_step: !!float 4e-2
time_step1: 0.04

gravity: [ 0, -9.8, 0 ]

spring_Y: 3e4

ball:
  radius: 0.3
  center: [ 0.23, 0, 0 ]