backend: gpu           # gpu|metal|vulkan|cpu

grid_size_x: 128
grid_size_y: 128

time_step: !!float 8e-3

gravity: [ 0, -9.8, 0 ]
dashpot_damping: !!float 1e4
drag_damping: 0.9

spring_Y: 3e4

ball:
  radius: 0.02
  color: [ 0.5, 0.42, 0.8 ]
  positions: [
    [ 0.1,  0.5, 0 ],
#    [ 0.1,  0.6, 0 ],
#    [ 0.2,  0.6, 0 ],
    [ 0.2,  0.5, 0 ],
  ]

window:
  resolution: [ 1024, 1024 ]

canvas:
  background_color: [ 1, 1, 1 ]


camera:
  position: [ 0.0, 0.0, 2 ]
  lookat: [ 0.0, 0.0, 0 ]

light:
  point:
    position: [ 0, 1, 2 ]
    color: [ 1, 1, 1 ]
  ambient:
    color: [ 1.0, 1.0, 1.0 ]
